# Generated by Django 4.0.4 on 2025-05-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileApk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apk_version', models.CharField(max_length=50)),
                ('apk_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mobile Apk',
                'verbose_name_plural': 'Mobile Apks',
                'db_table': 'mobile_apks',
            },
        ),
        migrations.CreateModel(
            name='MobileAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('passcode', models.CharField(max_length=256)),
                ('token', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'Mobile Assignment',
                'verbose_name_plural': 'Mobile Assignments',
                'db_table': 'mobile_assignments',
            },
        ),
    ]
