# Generated by Django 4.0.4 on 2025-05-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('v1_forms', '0001_initial'),
        ('v1_profile', '0001_initial'),
        ('v1_mobile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileassignment',
            name='administrations',
            field=models.ManyToManyField(to='v1_profile.administration'),
        ),
        migrations.AddField(
            model_name='mobileassignment',
            name='forms',
            field=models.ManyToManyField(to='v1_forms.forms'),
        ),
    ]
