"""
Django settings for mis project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import sys
from datetime import timedelta
from os import environ
from pathlib import Path

APP_NAME = environ.get("APP_NAME", "mis")
APP_SHORT_NAME = environ.get("APP_SHORT_NAME", "mis")
APK_SHORT_NAME = environ.get("APK_SHORT_NAME", "mis-mobile")
APK_NAME = environ.get("APK_NAME", "MIS mobile")
SHOW_LANDING_PAGE = environ.get("SHOW_LANDING_PAGE", "false").lower() == "true"

if 'SENTRY_DSN' in environ:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    sentry_environment = "production" if "PROD" in environ else "develop"
    sentry_sdk.init(
        dsn=environ['SENTRY_DSN'],
        # Set traces_sample_rate to 1.0 to capture 100%
        # of transactions for performance monitoring.
        environment=sentry_environment,
        traces_sample_rate=1.0,
        # Set profiles_sample_rate to 1.0 to profile 100%
        # of sampled transactions.
        # We recommend adjusting this value in production.
        profiles_sample_rate=1.0,
        ignore_errors=[
            "django.core.exceptions.PermissionDenied",
            "django.http.response.Http404",
            "django.http.response.HttpResponseNotFound",
            "django.http.response.HttpResponseForbidden",
            "django.http.response.HttpResponseBadRequest",
        ],
        integrations=[DjangoIntegration()]
    )

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = environ["DJANGO_SECRET"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if "DEBUG" in environ else False
PROD = True if "PROD" in environ else False
# True only when running under `manage.py test`. Used to keep legacy
# test-only conveniences (the admin@akvo.org auto-create on login) out of
# production code paths, and — since this iteration — to hold host
# routing off for the suite. Matched positionally, so a stray "test"
# argument to some other command cannot switch it on. Defined up here
# because BASE_DOMAIN below now depends on it.
TESTING = sys.argv[1:2] == ["test"]

# Host-based tenant routing. Unset means single-host: every host is the
# base domain, nothing resolves to a tenant, and the routing is inert —
# which is how the test suite and any non-SaaS deployment run.
#
# Forced off under `test` whatever the environment says. The Django test
# client's host is "testserver", which is nobody's base domain, so a
# BASE_DOMAIN inherited from a developer's .env would 404 the entire
# suite. The tests that exercise host routing opt back in with
# override_settings, which is how they read anyway.
BASE_DOMAIN = "" if TESTING else environ.get("BASE_DOMAIN", "")

# Origin that serves embedded dashboards' author markup, e.g.
# "https://embed.example.com". It MUST NOT be this application's origin:
# the whole point is that a pasted snippet runs somewhere its scripts
# cannot reach our DOM or the AUTH_TOKEN cookie (which is host-only, and
# readable from JavaScript). Unset means embedding is not configured for
# this deployment, and the viewer says so rather than falling back to
# serving the markup here -- that fallback would be the cross-site
# scripting hole the separate origin exists to prevent.
EMBED_HOST = environ.get("EMBED_HOST", "")


ALLOWED_HOSTS = ["*"]

# Application definition

# Default django apps
DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

# Add third party apps below
EXTERNAL_APPS = [
    "rest_framework",
    "rest_framework_simplejwt",
    "drf_spectacular",
    "django_dbml",
    "django_extensions",
    "django_q",
]

# Add API apps below
API_APPS = [
    "api.v1.v1_users",
    "api.v1.v1_profile",
    "api.v1.v1_forms",
    "api.v1.v1_data",
    "api.v1.v1_approval",
    "api.v1.v1_jobs",
    "api.v1.v1_mobile",
    "api.v1.v1_files",
    "api.v1.v1_visualization",
    "api.v1.v1_chatbot",
    "api.sentry_test",
]

# When two apps define a management command of the same name the one
# listed first here wins, so api.v1.v1_users precedes django.contrib.auth:
# its `createsuperuser` is the one that understands --tenant, and without
# this ordering the seeded superadmin lands in the tenant-less space.
INSTALLED_APPS = (
    ["api.v1.v1_users"]
    + DJANGO_APPS
    + [app for app in API_APPS if app != "api.v1.v1_users"]
    + EXTERNAL_APPS
)

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "middleware.tenant.TenantMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "middleware.user_activity.UserActivity",
]

ROOT_URLCONF = "mis.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [Path.joinpath(BASE_DIR, "mis/templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mis.wsgi.application"

# Rest Settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "api.v1.v1_mobile.authentication.AssignmentAwareJWTAuthentication",
    ),
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
    "DATE_FORMAT": "%d-%m-%Y",
    "DEFAULT_VERSION": "v1",
    "DATETIME_FORMAT": "%d-%m-%Y %H:%M:%S",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS":
    "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 10,
}
SPECTACULAR_SETTINGS = {
    "TITLE": APP_NAME,
    "DESCRIPTION": "",
    "VERSION": "1.0.0",
    "SORT_OPERATIONS": False,
    "COMPONENT_SPLIT_REQUEST": True,
}
# JWT Config
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=12),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=10),
    "AUTH_TOKEN_CLASSES": (
        "rest_framework_simplejwt.tokens.AccessToken",
        "api.v1.v1_mobile.authentication.MobileAssignmentToken",
    ),
}
# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": environ["DB_SCHEMA"],
        "USER": environ["DB_USER"],
        "PASSWORD": environ["DB_PASSWORD"],
        "HOST": environ["DB_HOST"],
        "PORT": "5432",
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation"
        ".UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation"
        ".MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation"
        ".CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation"
        ".NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

"""
The TIME_ZONE has been set to 'Pacific/Fiji'
to align with the application's focus on Fiji.
"""
TIME_ZONE = "Pacific/Fiji"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "static-files/"

# For Caching API call
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": "/var/tmp/cache",
    }
}
CACHE_FOLDER = "/tmp/cache/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "v1_users.SystemUser"

AUTHENTICATION_BACKENDS = [
    "utils.tenant_auth_backend.TenantAwareBackend",
]

# MOBILE ENV VARIABLES
WEBDOMAIN = environ.get("WEBDOMAIN", "http://localhost:3000")
APK_UPLOAD_SECRET = environ.get("APK_UPLOAD_SECRET")
MASTER_DATA = "./source"
STORAGE_PATH = environ.get("STORAGE_PATH", "./storage")

# AI CHATBOT ENV VARIABLES
OPENAI_API_KEY = environ.get("OPENAI_API_KEY", "")
OPENAI_ASSISTANT_ID = environ.get("OPENAI_ASSISTANT_ID", "")
OPENAI_VECTOR_STORE_ID = environ.get("OPENAI_VECTOR_STORE_ID", "")

FORM_GEO_VALUE = {"lat": -18.1236015, "lng": 178.3805867}  # Fiji coordinates
FORM_IMPORT_MAX_FILE_SIZE = int(
    environ.get("FORM_IMPORT_MAX_FILE_SIZE", 5 * 1024 * 1024)
)

BUCKET_NAME = "mis"
FAKE_STORAGE = False

# Mailjet everywhere by default; local development overrides EMAIL_BACKEND to
# Django's SMTP backend and points it at the Mailpit container, which accepts
# any message and shows it in a web inbox. Registration is the reason this
# matters: the activation link is the only way to finish signing up, so a
# developer with no mail provider could not exercise the flow at all.
EMAIL_BACKEND = environ.get(
    "EMAIL_BACKEND", "django_mailjet.backends.MailjetBackend"
)
# Only consulted when EMAIL_BACKEND is an SMTP one; Mailjet ignores them.
# The defaults are the local Mailpit container, so the compose override only
# has to switch the backend.
EMAIL_HOST = environ.get("EMAIL_HOST", "mailpit")
EMAIL_PORT = int(environ.get("EMAIL_PORT", 1025))
MAILJET_API_KEY = environ["MAILJET_APIKEY"]
MAILJET_API_SECRET = environ["MAILJET_SECRET"]
EMAIL_FROM = environ.get("EMAIL_FROM", "noreply@akvo.org")

COUNTRY_NAME = "fiji"

TEST_ENV = False

Q_CLUSTER = {
    "name": "DjangORM",
    "workers": 4,
    "timeout": 600,
    "retry": 1200,
    "queue_limit": 50,
    "bulk": 10,
    "orm": "default",
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "file": {
            "level": "WARNING",
            "class": "logging.FileHandler",
            "filename": f"{BASE_DIR}/logs/logfile.log",
        },
    },
    "loggers": {
        "your_app_name": {
            "handlers": ["file"],
            "level": "WARNING",
        },
    },
}
