# Generated by Django 4.0.4 on 2025-05-21 09:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=None, max_length=255, null=True)),
                ('name', models.TextField()),
                ('path', models.TextField(default=None, null=True)),
            ],
            options={
                'db_table': 'administrator',
            },
        ),
        migrations.CreateModel(
            name='AdministrationAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.CharField(choices=[('value', 'Value'), ('option', 'Option'), ('multiple_option', 'Multiple option'), ('aggregate', 'Aggregate')], default='value', max_length=25)),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), blank=True, default=list, size=None)),
            ],
            options={
                'db_table': 'administration_attribute',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'entities',
            },
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
            ],
            options={
                'db_table': 'levels',
            },
        ),
        migrations.CreateModel(
            name='EntityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('code', models.CharField(default=None, max_length=255, null=True)),
                ('administration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entity_data', to='v1_profile.administration')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entity_data', to='v1_profile.entity')),
            ],
            options={
                'db_table': 'entity_data',
            },
        ),
        migrations.CreateModel(
            name='AdministrationAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(default=dict)),
                ('administration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='v1_profile.administration')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1_profile.administrationattribute')),
            ],
            options={
                'db_table': 'administration_attribute_value',
            },
        ),
        migrations.AddField(
            model_name='administration',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrator_level', to='v1_profile.levels'),
        ),
        migrations.AddField(
            model_name='administration',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_administration', to='v1_profile.administration'),
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Super Admin'), (2, 'Admin')])),
                ('administration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_administration', to='v1_profile.administration')),
            ],
            options={
                'db_table': 'access',
            },
        ),
    ]
