# Generated by Django 4.0.4 on 2025-05-21 09:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.IntegerField(choices=[(1, 'Read'), (2, 'Edit'), (3, 'Approve')])),
            ],
            options={
                'db_table': 'user_form_access',
            },
        ),
        migrations.CreateModel(
            name='FormApprovalAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'form_approval_assignment',
            },
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('version', models.IntegerField(default=1)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('approval_instructions', models.JSONField(default=None, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Registration'), (2, 'Monitoring')], default=1)),
            ],
            options={
                'db_table': 'form',
            },
        ),
        migrations.CreateModel(
            name='QuestionAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None, null=True)),
                ('attribute', models.IntegerField(choices=[(1, 'chart'), (2, 'aggregate'), (3, 'table'), (4, 'jmp'), (5, 'advanced_filter')])),
                ('options', models.JSONField(default=None, null=True)),
            ],
            options={
                'db_table': 'question_attribute',
            },
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('label', models.TextField(default=None, null=True)),
                ('order', models.BigIntegerField(default=None, null=True)),
                ('repeatable', models.BooleanField(default=False)),
                ('repeat_text', models.CharField(default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'question_group',
            },
        ),
        migrations.CreateModel(
            name='QuestionOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.BigIntegerField(default=None, null=True)),
                ('label', models.TextField(default=None, null=True)),
                ('value', models.CharField(default=None, max_length=255, null=True)),
                ('other', models.BooleanField(default=False)),
                ('color', models.TextField(default=None, null=True)),
            ],
            options={
                'db_table': 'option',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.BigIntegerField(default=None, null=True)),
                ('label', models.TextField()),
                ('short_label', models.TextField(default=None, null=True)),
                ('name', models.CharField(default=None, max_length=255, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Geo'), (2, 'Administration'), (3, 'Text'), (4, 'Number'), (5, 'Option'), (6, 'Multiple_Option'), (7, 'Cascade'), (8, 'Photo'), (9, 'Date'), (10, 'Autofield'), (11, 'Attachment'), (12, 'Signature')])),
                ('meta', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=True)),
                ('rule', models.JSONField(default=None, null=True)),
                ('dependency', models.JSONField(default=None, null=True)),
                ('api', models.JSONField(default=None, null=True)),
                ('extra', models.JSONField(default=None, null=True)),
                ('tooltip', models.JSONField(default=None, null=True)),
                ('fn', models.JSONField(default=None, null=True)),
                ('pre', models.JSONField(default=None, null=True)),
                ('display_only', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='UserForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_user', to='v1_forms.forms')),
            ],
            options={
                'db_table': 'user_form',
            },
        ),
    ]
