# Generated by Django 4.0.4 on 2025-05-21 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('v1_forms', '0001_initial'),
        ('v1_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userforms',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_form', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questions',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_questions', to='v1_forms.forms'),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_group_question', to='v1_forms.questiongroup'),
        ),
        migrations.AddField(
            model_name='questionoptions',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='v1_forms.questions'),
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_question_group', to='v1_forms.forms'),
        ),
        migrations.AddField(
            model_name='questionattribute',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_question_attribute', to='v1_forms.questions'),
        ),
        migrations.AddField(
            model_name='forms',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='v1_forms.forms'),
        ),
        migrations.AddField(
            model_name='formapprovalassignment',
            name='administration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administration_data_approval', to='v1_profile.administration'),
        ),
        migrations.AddField(
            model_name='formapprovalassignment',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_data_approval', to='v1_forms.forms'),
        ),
        migrations.AddField(
            model_name='formapprovalassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_data_approval', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formaccess',
            name='user_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_form_access', to='v1_forms.userforms'),
        ),
        migrations.AlterUniqueTogether(
            name='userforms',
            unique_together={('user', 'form')},
        ),
        migrations.AddConstraint(
            model_name='questions',
            constraint=models.UniqueConstraint(fields=('form', 'name'), name='unique_form_question'),
        ),
        migrations.AlterUniqueTogether(
            name='questions',
            unique_together={('form', 'name')},
        ),
        migrations.AddConstraint(
            model_name='questionoptions',
            constraint=models.UniqueConstraint(fields=('question', 'value'), name='unique_question_option'),
        ),
        migrations.AlterUniqueTogether(
            name='questionoptions',
            unique_together={('question', 'value')},
        ),
        migrations.AddConstraint(
            model_name='questiongroup',
            constraint=models.UniqueConstraint(fields=('form', 'name'), name='unique_form_question_group'),
        ),
        migrations.AlterUniqueTogether(
            name='questiongroup',
            unique_together={('form', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='questionattribute',
            unique_together={('name', 'question', 'attribute', 'options')},
        ),
    ]
