# Generated by Django 4.0.4 on 2025-05-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0046_alter_questions_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='repeat_text',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='repeatable',
            field=models.BooleanField(default=False),
        ),
    ]
