# Generated by Django 4.0.4 on 2026-09-03 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0009_forms_tenant'),
        ('v1_visualization', '0003_dashboard_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='embed_snippet',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='kind',
            field=models.IntegerField(choices=[(1, 'widgets'), (2, 'embed')], default=1),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='root_form',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dashboards', to='v1_forms.forms'),
        ),
        migrations.AddConstraint(
            model_name='dashboard',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('embed_snippet__isnull', True), ('kind', 1), ('root_form__isnull', False)), models.Q(('embed_snippet__isnull', False), ('kind', 2), ('root_form__isnull', True), models.Q(('embed_snippet', ''), _negated=True)), _connector='OR'), name='dashboard_kind_matches_source'),
        ),
    ]
