# Generated by Django 4.0.4 on 2025-05-21 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('v1_data', '0001_initial'),
        ('v1_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingformdata',
            name='administration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administration_pending_form_data', to='v1_profile.administration'),
        ),
        migrations.AddField(
            model_name='pendingformdata',
            name='batch',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_pending_data_batch', to='v1_data.pendingdatabatch'),
        ),
    ]
