# Generated by Django 4.0.4 on 2025-04-30 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1_data', '0035_delete_viewdataoptions_delete_viewjmpcount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingdatabatchcomments',
            name='file_action',
            field=models.IntegerField(choices=[(1, 'Document added to the batch'), (2, 'Document has been changed'), (3, 'Document removed from the batch')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='pendingdatabatchcomments',
            name='file_path',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PendingDataBatchFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_files', to='v1_data.pendingdatabatch')),
            ],
            options={
                'verbose_name': 'Batch File',
                'verbose_name_plural': 'Batch Files',
                'db_table': 'batch_files',
            },
        ),
    ]
