# Generated by Django 4.0.4 on 2025-05-01 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1_data', '0036_pendingdatabatchcomments_file_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingdatabatch',
            name='file',
        ),
    ]
