# Generated by Django 4.0.4 on 2025-05-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(default=None, max_length=50, null=True, unique=True)),
                ('type', models.IntegerField(choices=[(1, 'send_email'), (2, 'validate_data'), (3, 'seed_data'), (4, 'download'), (5, 'download_administration'), (6, 'download_entities')])),
                ('status', models.IntegerField(choices=[(1, 'pending'), (2, 'on_progress'), (3, 'failed'), (4, 'done')], default=1)),
                ('attempt', models.IntegerField(default=0)),
                ('result', models.TextField(default=None, null=True)),
                ('info', models.JSONField(default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('available', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
    ]
